# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c61627fc7078f2410ab4c6e24044054c81032c7c92166b70f89b033d7d48321ef100a47c2ed630765bc9ec469cfbcf2f35530ca966b1b158ac2af2d1219f65ab

test:
  secret_key_base: 3199a334e5fe5a010e0e9e56f551a59f26b4e1c345a0d0d8264d3bfe7c62a0a788b5947b5ccf45e0dcb064b5d44e2c9c06ac280eaf5da670540dc878694ded0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
